views/security/login.php
Without these properties, in every keystroke typed on the username and password an ajax request is made trying to login. Lika a brute force attack.
I would also like to discuss with you a change in Ajax validation. It would be more performatic if the user is already redirected when no error occurs in the validation.
I'm doing this by extending the class and overriding the method:
```PHP
protected function performAjaxValidation(Model $model)
{
if (\Yii::$app->request->isAjax && $model->load(\Yii::$app->request->post())) {
$result = ActiveForm::validate($model);
\Yii::$app->response->format = Response::FORMAT_JSON;
if ($result === []) {
return $this->goBack();
}
echo json_encode($result);
\Yii::$app->end();
}
}
```
=> Avoid a flood of request on login form

models/User.php
When trying to confirm an email address with an invalid token it would render an error. It would also show a message saying the account has been successfully confirmed together with the message that the confirmation link is invalid or out-of-date.
I put everything in an else statement to prevent deleting non existing tokens or trying to log in a user with an invalid token.
I have not written any extra test for this as the test already check if
$I->see('Confirmation link is invalid or out-of-date. You can try requesting a new one.');
=> Bugfix: Tried to delete an non existing token

controllers/SettingsController.php
redirection went to /account and should take care of the current route.
the reason was missing brackets around 'account'
pls integrate into the next version.
thx.
=> redirect failed on actionConfirm()

docs/available-actions.md
Apparently it used to be `/user/settings/accounts`, but now it is `/user/settings/networks`
=> Corrected link to social networks settings page in doc

models/RegistrationForm.php, models/SettingsForm.php, models/User.php
I suggest update the username pattern to make it more suitable to reality.
- Do not allow special characters.
- Allow start with a number. This prohibition is very restrictive.
In a project work, the username is formed only by numbers, the registration code of the employee.
=> Update username pattern

views/admin/_info.php
fix for issue  #361
the confirmation time was actually showing the creation time.
=> Fix small bug in User Administration. Confirmation time not created time

CHANGELOG.md, migrations/m141222_135246_alter_username_length.php, models/RegistrationForm.php, models/User.php, tests/codeception/unit/RegistrationFormTest.php, views/admin/_user.php
A project i have done needed registration by email only,
so i have written every email into the username field.
This worked well, but the username field looks ugly with
all the emails truncated after char 25
I do not see the sense in limiting the username length.
Some people use longer usernames, and modern applications
should display them properly. Please consider to remote
the username character length limit.
=> Do not limit user->username length to 25 chars

CHANGELOG.md, views/admin/index.php
Not having the php-intl extension installed yields this error:
Not Supported – yii\base\NotSupportedException
Message format 'date' is not supported. You have to install PHP intl extension to use this feature.
This is a fallback for user not having installed this extension.
=> Ensure user/index works without php-intl extension

messages/message.php
If you do a composer install and run: vendor/bin/yii message/extract messages/message.php
It will also translate the vendor folder.
=> Exclude vendor dir from messages

Module.php
`registration/confirm` & `recovery/reset` field `<code>` may contain not only `\w` symbols
because it's use `\Yii::$app->security->generateRandomString()`
=> Update module routes

migrations/m150623_212711_fix_username_notnull.php
The last migration changed the field and allowed null.
=> fix username NOT NULL

migrations/Migration.php
The collate was set to `utf8_general_ci` but many developers uses `utf8_unicode_ci`.
I left `$tableOptions` property of `Migration` class to be null so tables charset and collate will be set to db default values.
I didn't remove the property in case someone wanted to set it different than db default.
Refs #443
=> Migration - don't force charset and collate in mysql

migrations/m140504_113157_update_tables.php, migrations/m141222_110026_update_ip_field.php
I manage all the migrations in my application automatically, including extensions' migrations.
A migration should be revertible.
I created the missing down functions in your migrations.
=> Migration::down() implementations

docs/custom-access-control.md
PHP Compile Error – yii\base\ErrorException
Cannot declare class app\filters\AccessRule because the name is already in use
php-fpm 5.5.9
=> Cannot declare class app\filters\AccessRule

clients/Google.php
Google returns multiple email adresses in an account. The client only recognizes one. Now updated it to pick the first of the returned emailadresses.
=> Fixed google auth to use first email of emails

models/Account.php, models/LoginForm.php, models/Profile.php, models/RecoveryForm.php, models/RegistrationForm.php, models/ResendForm.php, models/SettingsForm.php, models/Token.php, models/User.php, tests/codeception/_init.php, traits/ModuleTrait.php
This uses getters for the protected properties in the User model.
This is an improvement to the current implementation, but still it is not an ideal way of dependency injection.
=> Use getters instead of references to dependencies.

migrations/Migration.php
For mysql it is neccesary that the tables is in innodb.
=> Added tableOptions for mysql

views/mail/welcome.php
Double click on the password in the text of the letter, highlights the extra space.
" h5ErMcP2" -> "h5ErMcP2"
=> fix double-click selection within spaces before

Module.php, docs/configuration.md, models/User.php
Pull request for issue #385
Added OR condition to use RBAC permission checking (if configured) to
return true from User::getIsAdmin() if the user has the permission name
defined in Module::$adminPermission.
Updated documentation.
=> Admin access via RBAC permission for #385

controllers/AdminController.php
I had problems editing user profiles, if the profiles hadn't been created for some reason in the first place.
I looked through the code and while this is also a fix for my problem mentioned above, it looked more nicer to me to use event after the profile check.
=> fixed empty event on missing profile

events/ResetPasswordEvent.php, traits/EventTrait.php
Because it can be null if there is no record in the database (https://github.com/dektrium/yii2-user/blob/master/controllers/RecoveryController.php#L152)
=> Token as optional param

models/Profile.php
No protocol required, browsers can handle this automatically
=> Gravatar url change

models/User.php
Cosmetic change: 
In the current implementation the generated username becomes something like "user134" if the base email name is no longer availabe.
This patch uses "base-email-name<rowID>" instead so joe@xyz.com becomes joe953 instead of user953 in case of a name collision.
=> Use base email name for generated username

models/User.php
Fallback to safe naming scheme if email name is not a valid user name, fixes issue with PR #698
=> Fallback to safe generated user name

views/_alert.php, views/admin/_assignments.php
Alerts with "close"-Buttons should have the css-class "alert-dismissible"
to align the button properly.
Before patch:
After patch:
=> Add css-class "alert-dismissible" to alerts

migrations/m140209_132017_init.php, migrations/m140403_174025_create_account_table.php, migrations/m140504_113157_update_tables.php, migrations/m140504_130429_create_token_table.php, migrations/m140830_171933_fix_ip_field.php, migrations/m141222_110026_update_ip_field.php, migrations/m141222_135246_alter_username_length.php, migrations/m150614_103145_update_social_account_table.php, migrations/m150623_212711_fix_username_notnull.php, migrations/m151218_234654_add_timezone_to_profile.php
Update migrations syntax for Yii 2.0.6 changes and small fixes for code style.
=> Update migrations syntax

CHANGELOG.md, Module.php, README.md, controllers/AdminController.php, docs/user-management.md, messages/de/user.php, views/admin/index.php
Please check if there are any security concerns using this approach. Could the session param 'previous_user' be modified by an intruder somehow? Thanks.
=> Add ability to switch back to previous user when impersonated

models/LoginForm.php, models/RecoveryForm.php, models/RegistrationForm.php, models/SettingsForm.php, models/User.php
From [documentation](https://github.com/yiisoft/yii2/blob/master/docs/guide/input-validation.md):
> The validation rules are evaluated in the order they are listed.
Filters like `trim` should be placed before the validation rules. Otherwise, they will not participate in the previous validation rules.
| Fixed issues  | no
=> Fix filters in model rules

CHANGELOG.md, models/UserSearch.php
This seems to be a sane default setting. The probability is high that we want to deal with the most recent users first. Having an application with >10000 users this default settings would be nice.
=> Order by most recent registration first (created_at DESC) by default

controllers/RecoveryController.php
Just using an recovery token that does not exists you´ll get this internal error if you do not check for a Token object.
=> errorhandling recovery/reset token object

CHANGELOG.md, controllers/SecurityController.php
=> Fix: Update last_login_at when successfully logged in over oauth(#899)

migrations/Migration.php, migrations/m141222_110026_update_ip_field.php, migrations/m150614_103145_update_social_account_table.php
| Breaks BC?    | yes
This is a small refactoring so migrations use the injected `Connection` object instead of using the global service locator (`Yii::$app`).
=> Use `$this->db` instead of `Yii::$app->db` in migrations.

views/admin/index.php
>     * Tokens enclosed within curly brackets are treated as controller action IDs (also called *button names*
>     * in the context of action column). They will be replaced by the corresponding button rendering callbacks
>     * specified in [[buttons]]. For example, the token `{view}` will be replaced by the result of
>     * the callback `buttons['view']`. If a callback cannot be found, the token will be replaced with an empty string.
| Breaks BC?    | yes/no
| Fixed issues  | #890
=> ImpersonateUser fix

views/admin/index.php
resend password link was not visible bcz of typo mistake. 
It was allowing to non-admin ONLY. Now the link will be available for admin ONLY
| Is bugfix?    | yes/no
| New feature?  | yes/no
| Breaks BC?    | yes/no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
=> show resend password link

views/admin/index.php
Some behavior has been changes after #986
https://github.com/dektrium/yii2-user/commit/b7180b29f3f0673b4ee5f19f5974cc2e95b93cd6
see discussion https://github.com/dabilite/yii2-user/pull/10#discussion_r165061580
| Fixed issues  | related #1009 #893
=> fix isAdmin in admin/index action

clients/Google.php
Adds support for the hosted domain (hd) parameter (https://developers.google.com/identity/protocols/OpenIDConnect). This allows to restrict the login to users of a specific G Suite domain.
Example configuration:
```php
'google' => [
'class'        => 'dektrium\user\clients\Google',
'clientId'     => 'CLIENT_ID',
'clientSecret' => 'CLIENT_SECRET',
'hostedDomain' => 'mydomain.com',
],
```
| Fixed issues  |
=> Support for Googles hosted domain parameter
