dektrium/yii2-user

models/User.php
When trying to change/update an email address with an invalid token it would render an error. It would also show a message saying the account has been successfully confirmed together with the message that the confirmation link is invalid.
Just like in the last pull request for this file (User.php) I put everything in an else statement to prevent deleting non existing tokens or trying to log in a user with an invalid token.
=> Bugfix 2: Tried to delete an non existing token

views/settings/profile.php
Making this view/button style same as settings/account one (same style makes better experience for users + it's user friendly for mobile users)
=> adding css class to a button

models/User.php
Fix 2 cut and paste errors in comments
=> Correct a couple of comments in User.php

views/admin/_menu.php
Chainging "Yii::t('rbac'" to "Yii::t('user'" as there is no "rbac" language file. It's all in "user.php"
=> Fixing language problem

messages/pt-BR/user.php, views/security/login.php
Hello!
What do you think of including on the login screen a link to the user who does not have registration sign up?
=> Link to sign up on login screen

Mailer.php
We already have this parameter in the application. Do not you think best use it and avoid another variable to set an email address?
=> adminMail as default sender

controllers/SecurityController.php
It's bad show an error to the user and register a 403 in the log  :)
=> Redirect the user is already logged in.

models/LoginForm.php, models/Profile.php, models/RecoveryForm.php, models/RegistrationForm.php, models/ResendForm.php, models/SettingsForm.php, models/User.php, models/UserSearch.php
With the named rules, we have more freedom to work them when overriding the model.
For example, overwriting only the usernameLength rule.
=> Named rules

docs/getting-started.md
Just a little typo corrected (not=>now).
=> Typo corrected

.gitattributes, .gitignore
See https://github.com/yiisoft/yii2/issues/7812#issuecomment-88908822
=> Add .gitignore and .gitattributes

controllers/AdminController.php
=> Prevent error

views/mail/text/welcome.php
The html version of mailer view Welcome.php was updated. This change makes similar changes in the text version.
=> Update text/Welcome.php to match changes in html version

messages/pt-PT/user.php
A small typo correction in pt-PT
=> Typo correction user.php

views/admin/index.php
needed to override index.php without overriding _menu.php
with relative path it is necessary to copy(override) _menu.php too.
=> update view path

docs/troubleshooting.md
=> delete double of

clients/LinkedIn.php
=> Added client for LinkedIn #496

docs/usage-with-advanced-template.md
I had issues following the this documentation but in the end was able to install the module. So I just wanted to clarify some steps and add a new step to help others configure the module.
=> Clarify configuration instructions

models/RecoveryForm.php, models/User.php
=> Fix scenarios in User and RecoveryForm

migrations/m150623_212711_fix_username_notnull.php
=> migration fix for pgsql #526

Bootstrap.php
Added sourceLanguage module if the project has a different
=> add sourceLanguage

models/LoginForm.php
поиск пользователя производится до валидации, соответственно обрезание лишних пробелов при поиске по факту не происходило
=> trimming the extra spaces during the authorization

migrations/m150623_212711_fix_username_notnull.php
Migration down method actualized for postgresql
=> migration down fix for pgsql fixes dektrium/yii2-user#526

docs/README.md, docs/data-model.md
give somewhat more insight on what's going on at the database level
=> showing Yii2-user's data model

models/User.php
The previous coding was inconsistent.
=> fix user generate

messages/pt-BR/user.php
The translation said that a password was generated in the process.
=> Fix translate.

filters/AccessRule.php
=> check other roles/permissions

models/User.php
Not throw the error under the carpet  ;)
=> Expose error

helpers/Timezone.php
=> Phpdoc fix

composer.json, views/_alert.php, views/admin/_account.php, views/admin/_assignments.php, views/admin/_info.php, views/admin/_menu.php, views/admin/_profile.php, views/admin/_user.php, views/admin/create.php, views/admin/index.php, views/admin/update.php, views/mail/confirmation.php, views/mail/layouts/html.php, views/mail/recovery.php, views/mail/welcome.php, views/message.php, views/profile/show.php, views/recovery/request.php, views/recovery/reset.php, views/registration/connect.php, views/registration/register.php, views/registration/resend.php, views/security/login.php, views/settings/_menu.php, views/settings/account.php, views/settings/networks.php, views/settings/profile.php
| Q | A |
| --- | --- |
| Is bugfix? | yes |
| New feature? | no |
| Breaks BC? | no |
| Fixed issues | no |
=> added yii2-jui and fixed code style for views files

Module.php
I have some problems without it (404 error on `/user/security/auth?authclient=xxx` page).
With this change all ok (`/user/auth?authclient=xxx`).
| Fixed issues  | #813
=> Add auth action into urlRules

controllers/SecurityController.php
I don't see `blocked` action in this controller.
=> Unused AccessControl action

views/admin/index.php
| Breaks BC?    | /no
I wonder how this could go through the CI server.
@dmeroff: could you write a guide on how to set up the test environment so i can add some functional and unit tests to the project? Would love to do so, but can´t get it running.
=> add important { in views/admin/index.php

models/User.php
`registration_ip` was changed to `varchar`.
=> Fixed user model phpdoc

Mailer.php
=> Option to set mailer component

messages/uk/user.php
| Fixed issues   | Ukrainian translation in uk message language file
=> Fixed uk translation

views/settings/_menu.php, widgets/UserMenu.php
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
=> Widgetized the user menu.

messages/nl/user.php
=> Update Dutch translation

models/UserSearch.php, views/admin/index.php
=> allow to search for user id in admin/index view

messages/pt-BR/user.php
| Is bugfix?    |  yes
| New feature? | no
| Breaks BC?    |  no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
=> Added missing translation

clients/Twitter.php, docs/social-auth.md
| Is bugfix?    | yes/no
| New feature?  | yes/no
| Fixed issues  | 
Bugfix or feature depends of the point of view... With this change now the client will be able to obtain the twitter account email if the app special permissions has been requested.
=> added email to Twitter client

composer.json
| Breaks BC?    | yes/no
| Fixed issues  | #993, #992
=> For current tag php is 7.1.11 is possible

controllers/AdminController.php
avoid echo call
| Fixed issues  | #1002
=> Fix preserved/hidden error on create/update/update-account admin actions

models/UserSearch.php
| Fixed issues  | #1025
Fixes this, https://github.com/dektrium/yii2-user/issues/1025
There was a typo, a missing dot
=> Fix crash while searching a user by IP

docs/faq.md
Tell more about customization uii2-user
| Is bugfix?    | yno
| New feature?  | yes/no
=> How to use flash messages instead redirect to additional pages
